import type { StatutService, Clients, Freelancers, Administrateur, Messagerie, Service, Paiements, Wallet, ProfilFreelancers, Rang, Commentaires, Notifications, Signalement, Justifications, Avertissements } from "./Type";

// StatutService (toujours le même objet, pas 10 variations)
export const statutServiceMock: StatutService = {
  EN_ATTENTE: "en_attente",
  CONFIRME: "confirme",
  ANNULE: "annule",
  FINALISE: "finalise",
  REFUSE: "refuse",
};

// Clients - 10 données
export const clientsMock: Clients[] = [
  {
    id_client: 1,
    nom: "Kaboukoussou",
    prenom: "William",
    email: "william@gmail.com",
    Telephone: "066123456",
    photo: "https://picsum.photos/200",
    mot_de_passe: "123",
    date_creation: "2026-06-06",
  },
  {
    id_client: 2,
    nom: "Diop",
    prenom: "Aminata",
    email: "aminata.diop@gmail.com",
    Telephone: "077123456",
    photo: "https://picsum.photos/202",
    mot_de_passe: "Aminata123",
    date_creation: "2026-05-15",
  },
  {
    id_client: 3,
    nom: "Fofana",
    prenom: "Mamadou",
    email: "mamadou.fofana@yahoo.fr",
    Telephone: "070123456",
    photo: "https://picsum.photos/203",
    mot_de_passe: "Mamadou123",
    date_creation: "2026-04-20",
  },
  {
    id_client: 4,
    nom: "Kone",
    prenom: "Fatoumata",
    email: "fatou.kone@gmail.com",
    Telephone: "065123456",
    photo: "https://picsum.photos/204",
    mot_de_passe: "Fatou123",
    date_creation: "2026-06-01",
  },
  {
    id_client: 5,
    nom: "Traore",
    prenom: "Ibrahim",
    email: "ibrahim.traore@outlook.com",
    Telephone: "068123456",
    photo: "https://picsum.photos/205",
    mot_de_passe: "Ibrahim123",
    date_creation: "2026-05-25",
  },
  {
    id_client: 6,
    nom: "Ndiaye",
    prenom: "Marie",
    email: "marie.ndiaye@gmail.com",
    Telephone: "076123456",
    photo: "https://picsum.photos/206",
    mot_de_passe: "Marie123",
    date_creation: "2026-06-10",
  },
  {
    id_client: 7,
    nom: "Bamba",
    prenom: "Kadiatou",
    email: "kadia.bamba@yahoo.fr",
    Telephone: "069123456",
    photo: "https://picsum.photos/207",
    mot_de_passe: "Kadia123",
    date_creation: "2026-05-05",
  },
  {
    id_client: 8,
    nom: "Sow",
    prenom: "Ousmane",
    email: "ousmane.sow@gmail.com",
    Telephone: "078123456",
    photo: "https://picsum.photos/208",
    mot_de_passe: "Ousmane123",
    date_creation: "2026-04-28",
  },
  {
    id_client: 9,
    nom: "Diallo",
    prenom: "Aissatou",
    email: "aissatou.diallo@gmail.com",
    Telephone: "066987654",
    photo: "https://picsum.photos/209",
    mot_de_passe: "Aissa123",
    date_creation: "2026-06-12",
  },
  {
    id_client: 10,
    nom: "Cisse",
    prenom: "Modibo",
    email: "modibo.cisse@outlook.com",
    Telephone: "071123456",
    photo: "https://picsum.photos/210",
    mot_de_passe: "Modibo123",
    date_creation: "2026-05-30",
  },
];

// Freelancers - 10 données
export const freelancersMock: Freelancers[] = [
  {
    id_freelancer: 1,
    nom: "Mavoungou",
    prenom: "Jean",
    email: "jean@gmail.com",
    Telephone: "066654321",
    photo: "https://picsum.photos/201",
    mot_de_passe: "123",
    date_creation: "2026-06-06",
  },
  {
    id_freelancer: 2,
    nom: "Kouassi",
    prenom: "Paul",
    email: "paul.kouassi@gmail.com",
    Telephone: "077654321",
    photo: "https://picsum.photos/211",
    mot_de_passe: "Paul123",
    date_creation: "2026-05-10",
  },
  {
    id_freelancer: 3,
    nom: "Mensah",
    prenom: "Sophie",
    email: "sophie.mensah@yahoo.fr",
    Telephone: "070654321",
    photo: "https://picsum.photos/212",
    mot_de_passe: "Sophie123",
    date_creation: "2026-04-15",
  },
  {
    id_freelancer: 4,
    nom: "Yao",
    prenom: "Christophe",
    email: "christophe.yao@gmail.com",
    Telephone: "065654321",
    photo: "https://picsum.photos/213",
    mot_de_passe: "Christophe123",
    date_creation: "2026-06-02",
  },
  {
    id_freelancer: 5,
    nom: "Kone",
    prenom: "Rachel",
    email: "rachel.kone@gmail.com",
    Telephone: "068654321",
    photo: "https://picsum.photos/214",
    mot_de_passe: "Rachel123",
    date_creation: "2026-05-20",
  },
  {
    id_freelancer: 6,
    nom: "Diaby",
    prenom: "Mohamed",
    email: "mohamed.diaby@outlook.com",
    Telephone: "076654321",
    photo: "https://picsum.photos/215",
    mot_de_passe: "Mohamed123",
    date_creation: "2026-06-08",
  },
  {
    id_freelancer: 7,
    nom: "Traore",
    prenom: "Alice",
    email: "alice.traore@gmail.com",
    Telephone: "069654321",
    photo: "https://picsum.photos/216",
    mot_de_passe: "Alice123",
    date_creation: "2026-05-03",
  },
  {
    id_freelancer: 8,
    nom: "N'Guessan",
    prenom: "David",
    email: "david.nguessan@gmail.com",
    Telephone: "078654321",
    photo: "https://picsum.photos/217",
    mot_de_passe: "David123",
    date_creation: "2026-04-25",
  },
  {
    id_freelancer: 9,
    nom: "Camara",
    prenom: "Fatou",
    email: "fatou.camara@gmail.com",
    Telephone: "071654321",
    photo: "https://picsum.photos/218",
    mot_de_passe: "Fatou123",
    date_creation: "2026-06-11",
  },
  {
    id_freelancer: 10,
    nom: "Bamba",
    prenom: "Lamine",
    email: "lamine.bamba@gmail.com",
    Telephone: "072654321",
    photo: "https://picsum.photos/219",
    mot_de_passe: "Lamine123",
    date_creation: "2026-05-28",
  },
];

// Administrateur - 10 données
export const administrateursMock: Administrateur[] = [
  {
    id_admin: 1,
    nom: "Admin Principal",
    email: "admin@gmail.com",
    mot_de_passe: "123",
  },
  {
    id_admin: 2,
    nom: "Moderateur Alpha",
    email: "alpha.moderateur@admin.com",
    mot_de_passe: "Alpha2026",
  },
  {
    id_admin: 3,
    nom: "Superviseur Beta",
    email: "beta.superviseur@admin.com",
    mot_de_passe: "Beta2026",
  },
  {
    id_admin: 4,
    nom: "Gestionnaire Charlie",
    email: "charlie.gestion@admin.com",
    mot_de_passe: "Charlie123",
  },
  {
    id_admin: 5,
    nom: "Admin Support",
    email: "support.admin@admin.com",
    mot_de_passe: "Support456",
  },
  {
    id_admin: 6,
    nom: "Moderateur Delta",
    email: "delta.modo@admin.com",
    mot_de_passe: "Delta789",
  },
  {
    id_admin: 7,
    nom: "Super Admin",
    email: "super.admin@admin.com",
    mot_de_passe: "Super2026",
  },
  {
    id_admin: 8,
    nom: "Admin Technique",
    email: "tech.admin@admin.com",
    mot_de_passe: "Tech123",
  },
  {
    id_admin: 9,
    nom: "Controleur Echo",
    email: "echo.controle@admin.com",
    mot_de_passe: "Echo456",
  },
  {
    id_admin: 10,
    nom: "Admin Securite",
    email: "securite.admin@admin.com",
    mot_de_passe: "Secure789",
  },
];

// Messagerie - 10 données
export const messagesMock: Messagerie[] = [
  {
    id_message: 1,
    id_envoyeur: 1,
    id_receveur: 2,
    contenu_message: "Bonjour, je souhaite commander votre service.",
    date: "2026-06-06 14:30",
    Lu: false,
  },
  {
    id_message: 2,
    id_envoyeur: 2,
    id_receveur: 1,
    contenu_message: "Bonjour, avec plaisir ! Quel est votre projet ?",
    date: "2026-06-06 14:35",
    Lu: true,
  },
  {
    id_message: 3,
    id_envoyeur: 3,
    id_receveur: 4,
    contenu_message: "Pouvez-vous me faire un devis ?",
    date: "2026-06-07 09:15",
    Lu: false,
  },
  {
    id_message: 4,
    id_envoyeur: 4,
    id_receveur: 3,
    contenu_message: "Oui, je vous envoie cela dans la journée.",
    date: "2026-06-07 10:00",
    Lu: true,
  },
  {
    id_message: 5,
    id_envoyeur: 5,
    id_receveur: 6,
    contenu_message: "Merci pour votre travail, c'est parfait !",
    date: "2026-06-08 16:20",
    Lu: true,
  },
  {
    id_message: 6,
    id_envoyeur: 6,
    id_receveur: 5,
    contenu_message: "Avec plaisir, n'hésitez pas pour d'autres projets.",
    date: "2026-06-08 16:25",
    Lu: false,
  },
  {
    id_message: 7,
    id_envoyeur: 7,
    id_receveur: 8,
    contenu_message: "Le délai de livraison est de combien ?",
    date: "2026-06-09 11:00",
    Lu: true,
  },
  {
    id_message: 8,
    id_envoyeur: 8,
    id_receveur: 7,
    contenu_message: "Comptez environ 5 jours ouvrés.",
    date: "2026-06-09 11:05",
    Lu: false,
  },
  {
    id_message: 9,
    id_envoyeur: 9,
    id_receveur: 10,
    contenu_message: "Acceptez-vous les paiements par Mobile Money ?",
    date: "2026-06-10 08:45",
    Lu: true,
  },
  {
    id_message: 10,
    id_envoyeur: 10,
    id_receveur: 9,
    contenu_message: "Oui, absolument ! Tous les moyens sont acceptés.",
    date: "2026-06-10 08:50",
    Lu: false,
  },
];

// Service - 10 données
export const servicesMock: Service[] = [
  {
    id_service: 1,
    id_client: 1,
    id_freelancer: 1,
    intitule: "Création d'un logo",
    description: "Création d'un logo professionnel",
    statut: statutServiceMock,
    date_creation: "2026-06-06",
  },
  {
    id_service: 2,
    id_client: 2,
    id_freelancer: 2,
    intitule: "Développement site vitrine",
    description: "Site web professionnel responsive",
    statut: statutServiceMock,
    date_creation: "2026-06-07",
  },
  {
    id_service: 3,
    id_client: 3,
    id_freelancer: 3,
    intitule: "Rédaction articles SEO",
    description: "10 articles optimisés SEO",
    statut: statutServiceMock,
    date_creation: "2026-06-08",
  },
  {
    id_service: 4,
    id_client: 4,
    id_freelancer: 4,
    intitule: "Traduction anglais-français",
    description: "Traduction de documents techniques",
    statut: statutServiceMock,
    date_creation: "2026-06-09",
  },
  {
    id_service: 5,
    id_client: 5,
    id_freelancer: 5,
    intitule: "Montage vidéo",
    description: "Montage vidéo professionnel 4K",
    statut: statutServiceMock,
    date_creation: "2026-06-10",
  },
  {
    id_service: 6,
    id_client: 6,
    id_freelancer: 6,
    intitule: "Design UI/UX",
    description: "Design complet d'application mobile",
    statut: statutServiceMock,
    date_creation: "2026-06-11",
  },
  {
    id_service: 7,
    id_client: 7,
    id_freelancer: 7,
    intitule: "Community management",
    description: "Gestion des réseaux sociaux",
    statut: statutServiceMock,
    date_creation: "2026-06-12",
  },
  {
    id_service: 8,
    id_client: 8,
    id_freelancer: 8,
    intitule: "Photographie produit",
    description: "Séance photo professionnelle",
    statut: statutServiceMock,
    date_creation: "2026-06-13",
  },
  {
    id_service: 9,
    id_client: 9,
    id_freelancer: 9,
    intitule: "Développement API REST",
    description: "Création d'API sécurisée",
    statut: statutServiceMock,
    date_creation: "2026-06-14",
  },
  {
    id_service: 10,
    id_client: 10,
    id_freelancer: 10,
    intitule: "Coaching digital",
    description: "Formation marketing digital",
    statut: statutServiceMock,
    date_creation: "2026-06-15",
  },
];

// Paiements - 10 données
export const paiementsMock: Paiements[] = [
  {
    id_paiement: 1,
    id_service: 1,
    id_client: 1,
    id_freelancer: 1,
    montant_ajoute: 50000,
  },
  {
    id_paiement: 2,
    id_service: 2,
    id_client: 2,
    id_freelancer: 2,
    montant_ajoute: 150000,
  },
  {
    id_paiement: 3,
    id_service: 3,
    id_client: 3,
    id_freelancer: 3,
    montant_ajoute: 75000,
  },
  {
    id_paiement: 4,
    id_service: 4,
    id_client: 4,
    id_freelancer: 4,
    montant_ajoute: 100000,
  },
  {
    id_paiement: 5,
    id_service: 5,
    id_client: 5,
    id_freelancer: 5,
    montant_ajoute: 200000,
  },
  {
    id_paiement: 6,
    id_service: 6,
    id_client: 6,
    id_freelancer: 6,
    montant_ajoute: 300000,
  },
  {
    id_paiement: 7,
    id_service: 7,
    id_client: 7,
    id_freelancer: 7,
    montant_ajoute: 120000,
  },
  {
    id_paiement: 8,
    id_service: 8,
    id_client: 8,
    id_freelancer: 8,
    montant_ajoute: 80000,
  },
  {
    id_paiement: 9,
    id_service: 9,
    id_client: 9,
    id_freelancer: 9,
    montant_ajoute: 250000,
  },
  {
    id_paiement: 10,
    id_service: 10,
    id_client: 10,
    id_freelancer: 10,
    montant_ajoute: 95000,
  },
];

// Wallet - 10 données
export const walletsMock: Wallet[] = [
  {
    id_wallet: 1,
    id_client: 1,
    id_freelancer: null,
    montant: 100000,
    devise: "XAF",
  },
  {
    id_wallet: 2,
    id_client: 2,
    id_freelancer: null,
    montant: 250000,
    devise: "XAF",
  },
  {
    id_wallet: 3,
    id_client: 3,
    id_freelancer: null,
    montant: 75000,
    devise: "XAF",
  },
  {
    id_wallet: 4,
    id_client: 4,
    id_freelancer: null,
    montant: 180000,
    devise: "XAF",
  },
  {
    id_wallet: 5,
    id_client: 5,
    id_freelancer: null,
    montant: 320000,
    devise: "XAF",
  },
  {
    id_wallet: 6,
    id_client: null,
    id_freelancer: 1,
    montant: 150000,
    devise: "XAF",
  },
  {
    id_wallet: 7,
    id_client: null,
    id_freelancer: 2,
    montant: 50000,
    devise: "XAF",
  },
  {
    id_wallet: 8,
    id_client: null,
    id_freelancer: 3,
    montant: 280000,
    devise: "XAF",
  },
  {
    id_wallet: 9,
    id_client: 6,
    id_freelancer: null,
    montant: 450000,
    devise: "XAF",
  },
  {
    id_wallet: 10,
    id_client: null,
    id_freelancer: 4,
    montant: 98000,
    devise: "XAF",
  },
];

// ProfilFreelancers - 10 données
export const profilsFreelancersMock: ProfilFreelancers[] = [
  {
    id_profil: 1,
    id_freelancer: 1,
    secteur_activite: "Informatique",
    profession: "Développeur React Native",
    descritpion: "Développeur mobile avec 5 ans d'expérience",
    document: "cv_jean.pdf",
  },
  {
    id_profil: 2,
    id_freelancer: 2,
    secteur_activite: "Design",
    profession: "Graphiste 3D",
    descritpion: "Spécialiste en modélisation 3D",
    document: "portfolio_paul.pdf",
  },
  {
    id_profil: 3,
    id_freelancer: 3,
    secteur_activite: "Marketing",
    profession: "Community Manager",
    descritpion: "Expert en stratégie digitale",
    document: "certificats_sophie.pdf",
  },
  {
    id_profil: 4,
    id_freelancer: 4,
    secteur_activite: "Rédaction",
    profession: "Copywriter SEO",
    descritpion: "Rédacteur web certifié",
    document: "cv_christophe.pdf",
  },
  {
    id_profil: 5,
    id_freelancer: 5,
    secteur_activite: "Vidéo",
    profession: "Monteur vidéo",
    descritpion: "Montage sur Premiere Pro",
    document: "showreel_rachel.pdf",
  },
  {
    id_profil: 6,
    id_freelancer: 6,
    secteur_activite: "Informatique",
    profession: "Développeur Full Stack",
    descritpion: "Spécialisé React et Node.js",
    document: "cv_mohamed.pdf",
  },
  {
    id_profil: 7,
    id_freelancer: 7,
    secteur_activite: "Photographie",
    profession: "Photographe professionnel",
    descritpion: "Studio photo et reportage",
    document: "portfolio_alice.pdf",
  },
  {
    id_profil: 8,
    id_freelancer: 8,
    secteur_activite: "Traduction",
    profession: "Traducteur assermenté",
    descritpion: "Traduction technique et juridique",
    document: "diplomes_david.pdf",
  },
  {
    id_profil: 9,
    id_freelancer: 9,
    secteur_activite: "Formation",
    profession: "Formateur en digital",
    descritpion: "Formation certifiante",
    document: "cv_fatou.pdf",
  },
  {
    id_profil: 10,
    id_freelancer: 10,
    secteur_activite: "Consulting",
    profession: "Consultant SEO",
    descritpion: "Optimisation et stratégie SEO",
    document: "certifications_lamine.pdf",
  },
];

// Rang - 10 données
export const rangsMock: Rang[] = [
  {
    id_rang: 1,
    id_freelancer: 1,
    rang: "expert",
  },
  {
    id_rang: 2,
    id_freelancer: 2,
    rang: "expert",
  },
  {
    id_rang: 3,
    id_freelancer: 3,
    rang: "intermédiaire",
  },
  {
    id_rang: 4,
    id_freelancer: 4,
    rang: "niveau_débutant",
  },
  {
    id_rang: 5,
    id_freelancer: 5,
    rang: "expert",
  },
  {
    id_rang: 6,
    id_freelancer: 6,
    rang: "expert",
  },
  {
    id_rang: 7,
    id_freelancer: 7,
    rang: "intermédiaire",
  },
  {
    id_rang: 8,
    id_freelancer: 8,
    rang: "niveau_débutant",
  },
  {
    id_rang: 9,
    id_freelancer: 9,
    rang: "expert",
  },
  {
    id_rang: 10,
    id_freelancer: 10,
    rang: "expert",
  },
];

// Commentaires - 10 données
export const commentairesMock: Commentaires[] = [
  {
    id_commentaire: 1,
    id_client: 1,
    id_freelancer: 1,
    commentaire: "Je recommande fortement ce freelancer.",
    date: "2026-06-06",
  },
  {
    id_commentaire: 2,
    id_client: 2,
    id_freelancer: 2,
    commentaire: "Travail de qualité, respect des délais.",
    date: "2026-06-07",
  },
  {
    id_commentaire: 3,
    id_client: 3,
    id_freelancer: 3,
    commentaire: "Très professionnel, à l'écoute.",
    date: "2026-06-08",
  },
  {
    id_commentaire: 4,
    id_client: 4,
    id_freelancer: 4,
    commentaire: "Excellent travail, je suis satisfait.",
    date: "2026-06-09",
  },
  {
    id_commentaire: 5,
    id_client: 5,
    id_freelancer: 5,
    commentaire: "Livraison rapide, bonne communication.",
    date: "2026-06-10",
  },
  {
    id_commentaire: 6,
    id_client: 6,
    id_freelancer: 6,
    commentaire: "Un peu cher mais qualité au rendez-vous.",
    date: "2026-06-11",
  },
  {
    id_commentaire: 7,
    id_client: 7,
    id_freelancer: 7,
    commentaire: "À refaire sans hésitation.",
    date: "2026-06-12",
  },
  {
    id_commentaire: 8,
    id_client: 8,
    id_freelancer: 8,
    commentaire: "Très bon suivi client.",
    date: "2026-06-13",
  },
  {
    id_commentaire: 9,
    id_client: 9,
    id_freelancer: 9,
    commentaire: "Compétences techniques solides.",
    date: "2026-06-14",
  },
  {
    id_commentaire: 10,
    id_client: 10,
    id_freelancer: 10,
    commentaire: "Service client réactif et efficace.",
    date: "2026-06-15",
  },
];

// Notifications - 10 données
export const notificationsMock: Notifications[] = [
  {
    id_notification: 1,
    id_client: 1,
    id_freelancer: null,
    id_admin: null,
    notification: "Votre commande a été confirmée.",
  },
  {
    id_notification: 2,
    id_client: null,
    id_freelancer: 1,
    id_admin: null,
    notification: "Vous avez reçu un nouveau paiement.",
  },
  {
    id_notification: 3,
    id_client: 2,
    id_freelancer: null,
    id_admin: null,
    notification: "Votre service est en cours de traitement.",
  },
  {
    id_notification: 4,
    id_client: null,
    id_freelancer: 2,
    id_admin: null,
    notification: "Nouveau message dans votre boîte.",
  },
  {
    id_notification: 5,
    id_client: 3,
    id_freelancer: null,
    id_admin: null,
    notification: "Rappel : validation de commande.",
  },
  {
    id_notification: 6,
    id_client: null,
    id_freelancer: 3,
    id_admin: null,
    notification: "Vous avez reçu un nouveau commentaire.",
  },
  {
    id_notification: 7,
    id_client: 4,
    id_freelancer: null,
    id_admin: null,
    notification: "Votre paiement a été validé.",
  },
  {
    id_notification: 8,
    id_client: null,
    id_freelancer: 4,
    id_admin: null,
    notification: "Un client souhaite modifier sa commande.",
  },
  {
    id_notification: 9,
    id_client: null,
    id_freelancer: null,
    id_admin: 1,
    notification: "Nouveau signalement à traiter.",
  },
  {
    id_notification: 10,
    id_client: 5,
    id_freelancer: null,
    id_admin: null,
    notification: "Promotion : frais réduits cette semaine.",
  },
];
export const signalementsMock: Signalement[] = [
  { id_signalement: 1,  id_signaleur: 1, signaleur_type: "client",     id_signalé: 2, Signalement: "Comportement inapproprié lors de l'échange de messages.",      statut: "en_attente", date: "12 mai 2026", categorie: "Comportement",  note_admin: "" },
  { id_signalement: 2,  id_signaleur: 3, signaleur_type: "freelancer", id_signalé: 4, Signalement: "Client refuse de payer après la livraison du travail.",          statut: "en_cours",   date: "10 mai 2026", categorie: "Paiement",      note_admin: "Enquête en cours." },
  { id_signalement: 3,  id_signaleur: 5, signaleur_type: "client",     id_signalé: 6, Signalement: "Travail livré ne correspond pas aux spécifications convenues.",   statut: "resolu",     date: "08 mai 2026", categorie: "Qualité",       note_admin: "Remboursement partiel effectué." },
  { id_signalement: 4,  id_signaleur: 1, signaleur_type: "client",     id_signalé: 8, Signalement: "Le freelancer a encaissé le paiement sans jamais livrer.",        statut: "en_attente", date: "05 mai 2026", categorie: "Arnaque",       note_admin: "" },
  { id_signalement: 5,  id_signaleur: 2, signaleur_type: "freelancer", id_signalé: 5, Signalement: "Messages harcelants envoyés en dehors des heures de travail.",    statut: "resolu",     date: "02 mai 2026", categorie: "Harcèlement",   note_admin: "Avertissement envoyé au client." },
  { id_signalement: 6,  id_signaleur: 3, signaleur_type: "freelancer", id_signalé: 1, Signalement: "Client a publié des informations fausses sur le profil.",         statut: "rejete",     date: "30 avr 2026", categorie: "Fausse info",   note_admin: "Signalement non fondé après vérification." },
  { id_signalement: 7,  id_signaleur: 4, signaleur_type: "client",     id_signalé: 3, Signalement: "Freelancer utilise des photos de profil frauduleuses.",           statut: "en_cours",   date: "28 avr 2026", categorie: "Fraude",        note_admin: "" },
  { id_signalement: 8,  id_signaleur: 6, signaleur_type: "freelancer", id_signalé: 7, Signalement: "Demandes répétées de services gratuits sous pression.",           statut: "resolu",     date: "25 avr 2026", categorie: "Comportement",  note_admin: "Compte banni." },
  { id_signalement: 9,  id_signaleur: 5, signaleur_type: "client",     id_signalé: 2, Signalement: "Qualité du service bien inférieure à ce qui était annoncé.",      statut: "en_attente", date: "22 avr 2026", categorie: "Qualité",       note_admin: "" },
  { id_signalement: 10, id_signaleur: 8, signaleur_type: "freelancer", id_signalé: 4, Signalement: "Ce client a tenté d'obtenir des services non inclus dans le prix.", statut: "en_attente", date: "20 avr 2026", categorie: "Paiement",    note_admin: "" },
];

// Justifications - 10 données
export const justificationsMock: Justifications[] = [
  {
    id_justification: 1,
    id_signalement: 1,
    Justification: "Le problème a été résolu après discussion.",
  },
  {
    id_justification: 2,
    id_signalement: 2,
    Justification: "Retard dû à un problème technique majeur.",
  },
  {
    id_justification: 3,
    id_signalement: 3,
    Justification: "Le client avait modifié ses exigences.",
  },
  {
    id_justification: 4,
    id_signalement: 4,
    Justification: "Sources citées et autorisées.",
  },
  {
    id_justification: 5,
    id_signalement: 5,
    Justification: "Malentendu, échanges apaisés ensuite.",
  },
  {
    id_justification: 6,
    id_signalement: 6,
    Justification: "Preuves fournies démontrant la bonne foi.",
  },
  {
    id_justification: 7,
    id_signalement: 7,
    Justification: "Paiement effectué après rappel.",
  },
  {
    id_justification: 8,
    id_signalement: 8,
    Justification: "Informations mises à jour et vérifiées.",
  },
  {
    id_justification: 9,
    id_signalement: 9,
    Justification: "Alerte à la sécurité de la plateforme.",
  },
  {
    id_justification: 10,
    id_signalement: 10,
    Justification: "Délai supplémentaire accordé par le client.",
  },
];

// Avertissements - 10 données
export const avertissementsMock: Avertissements[] = [
  {
    id_avertissement: 1,
    id_client: 1,
    id_freelancer: null,
    id_admin: 1,
    contenu_avertissement: "Veuillez respecter les règles de la plateforme.",
  },
  {
    id_avertissement: 2,
    id_client: null,
    id_freelancer: 1,
    id_admin: 2,
    contenu_avertissement: "Retard récurrent dans les livraisons.",
  },
  {
    id_avertissement: 3,
    id_client: 2,
    id_freelancer: null,
    id_admin: 3,
    contenu_avertissement: "Annulation abusive de commandes.",
  },
  {
    id_avertissement: 4,
    id_client: null,
    id_freelancer: 2,
    id_admin: 4,
    contenu_avertissement: "Communication inappropriée avec les clients.",
  },
  {
    id_avertissement: 5,
    id_client: 3,
    id_freelancer: null,
    id_admin: 5,
    contenu_avertissement: "Non-paiement des services commandés.",
  },
  {
    id_avertissement: 6,
    id_client: null,
    id_freelancer: 3,
    id_admin: 6,
    contenu_avertissement: "Travail non conforme aux normes de qualité.",
  },
  {
    id_avertissement: 7,
    id_client: 4,
    id_freelancer: null,
    id_admin: 7,
    contenu_avertissement: "Signalements multiples pour comportement abusif.",
  },
  {
    id_avertissement: 8,
    id_client: null,
    id_freelancer: 4,
    id_admin: 8,
    contenu_avertissement: "Suspicion de faux avis positifs.",
  },
  {
    id_avertissement: 9,
    id_client: 5,
    id_freelancer: null,
    id_admin: 9,
    contenu_avertissement: "Tentative de contournement des frais.",
  },
  {
    id_avertissement: 10,
    id_client: null,
    id_freelancer: 5,
    id_admin: 10,
    contenu_avertissement: "Partage de liens externes non autorisés.",
  },
];
